
import React from 'react';

export const SRSViewer: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Informational Banner */}
      <div className="bg-emerald-600 rounded-2xl p-4 px-6 flex items-center justify-between text-white shadow-lg shadow-emerald-900/10 border border-emerald-500">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-emerald-500/50 rounded-lg">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          </div>
          <p className="text-sm font-bold tracking-tight">
            Reference Material: System design and requirement documentation for administrators and reviewers.
          </p>
        </div>
        <span className="hidden lg:block text-[10px] font-black uppercase tracking-widest bg-emerald-700/50 px-3 py-1 rounded-full">Read Only</span>
      </div>

      <div className="bg-white border border-slate-200 rounded-3xl shadow-xl overflow-hidden p-8 lg:p-12">
        <div className="border-b border-slate-100 pb-8 mb-8">
          <h1 className="text-3xl font-black text-slate-900 leading-tight">Software Requirements Specification</h1>
          <p className="text-xl text-emerald-600 font-bold mt-2">Smart Campus Plastic Waste Monitoring Dashboard</p>
          <div className="flex gap-4 mt-6">
            <span className="bg-slate-100 text-slate-600 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest">Version 1.0</span>
            <span className="bg-slate-100 text-slate-600 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest">Released: Feb 2024</span>
            <span className="bg-emerald-50 text-emerald-700 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest">Status: Final Review</span>
          </div>
        </div>

        <div className="space-y-12 text-slate-700">
          {/* Section 1 */}
          <section>
            <h2 className="text-lg font-bold text-slate-900 border-l-4 border-emerald-500 pl-4 mb-4">1. Introduction</h2>
            <div className="space-y-4 ml-5">
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">1.1 Purpose</h3>
                <p className="text-sm leading-relaxed">
                  The purpose of this system is to provide a central, visual dashboard for campus administrators to monitor the status of IoT-enabled plastic waste bins. 
                  The goal is to increase efficiency in waste collection by identifying bins that require immediate attention, thereby promoting a cleaner, more sustainable campus.
                </p>
              </div>
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">1.2 Scope</h3>
                <p className="text-sm leading-relaxed">
                  This project focuses strictly on the <strong>frontend web dashboard</strong>. It visualizes data received from a sensor network (currently mocked for demonstration). 
                  The scope includes real-time status updates, alerts for full bins, and system health monitoring. Backend control systems and hardware assembly are considered outside this specific software scope.
                </p>
              </div>
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">1.3 Intended Audience</h3>
                <ul className="list-disc list-inside text-sm space-y-1 mt-2">
                  <li>Campus Administrators (primary decision-makers)</li>
                  <li>Monitoring Staff (responsible for collection)</li>
                  <li>Hackathon Judges (evaluators of system logic)</li>
                  <li>Future Developers (students looking to scale the project)</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-lg font-bold text-slate-900 border-l-4 border-emerald-500 pl-4 mb-4">2. Overall Description</h2>
            <div className="space-y-4 ml-5">
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">2.1 Product Perspective</h3>
                <p className="text-sm leading-relaxed">
                  This dashboard is a component of a larger "Smart Campus" initiative. It functions as the presentation layer, consuming data generated by ultrasonic sensors located within specialized plastic waste bins distributed across the campus.
                </p>
              </div>
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">2.2 Product Functions</h3>
                <ul className="list-disc list-inside text-sm space-y-1 mt-2">
                  <li>Real-time visualization of fill levels for multiple bins.</li>
                  <li>Color-coded status indicators (Empty, Medium, Full).</li>
                  <li>System-wide health monitoring (Battery levels, Connection status).</li>
                  <li>Live activity logging for recent sensor events.</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-slate-800 text-sm mb-1 uppercase tracking-wide">2.3 User Classes</h3>
                <p className="text-sm leading-relaxed">
                  <strong>Admin/Monitor:</strong> Requires high-level visibility of all campus zones. Does not need deep technical knowledge. Needs quick indicators for "Action Needed" areas.
                </p>
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-lg font-bold text-slate-900 border-l-4 border-emerald-500 pl-4 mb-4">3. System Features</h2>
            <div className="space-y-6 ml-5">
              <FeatureItem title="3.1 Header Module" desc="Fixed at top. Shows current navigation status and system-wide online indicator." />
              <FeatureItem title="3.2 Primary Bin Cards" desc="Card-based UI showing Bin ID, location, fill percentage, and a visual progress bar." />
              <FeatureItem title="3.3 System Status Module" desc="Displays counts of bins needing attention and average system battery health." />
              <FeatureItem title="3.4 Navigation Module" desc="Sidebar providing access to Dashboard, Logs, and Settings (placeholder)." />
            </div>
          </section>

          {/* Section 4/5 Combined */}
          <section className="bg-emerald-50 rounded-2xl p-6 border border-emerald-100">
             <h2 className="text-lg font-bold text-emerald-900 mb-4">4. Design Constraints & Non-Functional Requirements</h2>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-bold text-emerald-800 text-xs uppercase mb-2">Usability</h4>
                  <p className="text-[13px]">Clean, eco-friendly green palette. No training required for campus staff.</p>
                </div>
                <div>
                  <h4 className="font-bold text-emerald-800 text-xs uppercase mb-2">Performance</h4>
                  <p className="text-[13px]">Built with React for sub-second page transitions and minimal load times.</p>
                </div>
                <div>
                  <h4 className="font-bold text-emerald-800 text-xs uppercase mb-2">Scalability</h4>
                  <p className="text-[13px]">Designed to handle up to 500 sensors without layout breaking.</p>
                </div>
                <div>
                  <h4 className="font-bold text-emerald-800 text-xs uppercase mb-2">Eco-Theme</h4>
                  <p className="text-[13px]">Focus on Emerald/Green tones to align with sustainability goals.</p>
                </div>
             </div>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-lg font-bold text-slate-900 border-l-4 border-emerald-500 pl-4 mb-4">7. Future Enhancements</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 ml-5">
              <FutureTag text="Real Firebase/DB Integration" />
              <FutureTag text="Automated SMS Notifications for Sweepers" />
              <FutureTag text="Optimal Waste Truck Route Mapping" />
              <FutureTag text="Mobile App Version (PWA)" />
              <FutureTag text="Historical Analytics & Carbon Credits" />
            </div>
          </section>

          <section className="pt-10 border-t border-slate-100 text-center">
            <p className="text-xs text-slate-400 italic">Prepared for Semester 6 Mini Project & Hackathon Competition</p>
          </section>
        </div>
      </div>
    </div>
  );
};

const FeatureItem: React.FC<{ title: string; desc: string }> = ({ title, desc }) => (
  <div>
    <h3 className="font-bold text-slate-800 text-sm mb-1">{title}</h3>
    <p className="text-sm leading-relaxed">{desc}</p>
  </div>
);

const FutureTag: React.FC<{ text: string }> = ({ text }) => (
  <div className="flex items-center gap-2 p-3 bg-slate-50 border border-slate-100 rounded-xl">
    <div className="w-1.5 h-1.5 rounded-full bg-emerald-400"></div>
    <span className="text-xs font-medium text-slate-600">{text}</span>
  </div>
);
